version: '3.7'
services: 
  app:
    build:
      context: .
    image: uas/project-uas-cloud
    container_name: project-uas-cloud
    ports:
      - 3000:3000
    volumes:
      - ./:/var/www/html
    networks:
      - backend

  mysql:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_DATABASE: mykost
      MYSQL_USER: uas
      MYSQL_PASSWORD: Uas*1234
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - /opt/data:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
    name: backend-network
